version: "3"

services:
  mysql:
    build:
      context: ./db
    ports:
      - 3306:3306
    volumes:
      - ./db/var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
  phpfpm:
    build:
      context: ./app
    volumes:
      - ../template-ph3-study:/work/backend
    depends_on: ["mysql"]
  nginx:
    build:
      context: ./web
    ports:
      - 80:80
    volumes:
      - ../template-ph3-study:/work/backend
    depends_on: ["phpfpm"]

  app:
    image: node:lts # バージョン指定も可能 ex. node:12.16.1
    container_name: node.js
    tty: true
    volumes:
      - ./src:/src
    working_dir: "/src"